### ISSUE TITLE
Next Run and Last Run attributes didn't show dates

### ISSUE THREAD

**Issue by john-yousef** [BCornelissen/SCOM-WinTaskSchedulerMP#15] opened 2022-07-19 13:02 UTC
Hello ,
This is a question regarding the Last Run and Next Run attributes it shows "HasDate" string, is there a way to make these attributes to show the actual date and time on the scheduled task?

![image](https://user-images.githubusercontent.com/43895921/179756221-826301c4-bb00-4467-988d-21f717803691.png)

**Comment by BCornelissen** [comment] 2022-08-22 09:53
Hello John. The reason why it has that there, is because otherwise at every discovery interval, that property would change. This would cause new discoveries at every interval, which is a config churn issue on SCOM side. It is a by design item. The next run hasdate is just an indication that there seems to be a schedule assigned to the scheduled task.

**Closed as not planned** 2022-08-22 09:53 UTC
